/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as InterviewNewRouteImport } from './routes/interview.new'
import { Route as InterviewIdIndexRouteImport } from './routes/interview.$id.index'
import { Route as InterviewIdResultRouteImport } from './routes/interview.$id.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewNewRoute = InterviewNewRouteImport.update({
  id: '/interview/new',
  path: '/interview/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdIndexRoute = InterviewIdIndexRouteImport.update({
  id: '/interview/$id/',
  path: '/interview/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdResultRoute = InterviewIdResultRouteImport.update({
  id: '/interview/$id/result',
  path: '/interview/$id/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/$id/result': typeof InterviewIdResultRoute
  '/interview/$id/': typeof InterviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/$id/result': typeof InterviewIdResultRoute
  '/interview/$id': typeof InterviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/$id/result': typeof InterviewIdResultRoute
  '/interview/$id/': typeof InterviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/practice'
    | '/interview/new'
    | '/interview/$id/result'
    | '/interview/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/practice'
    | '/interview/new'
    | '/interview/$id/result'
    | '/interview/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/practice'
    | '/interview/new'
    | '/interview/$id/result'
    | '/interview/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  PracticeRoute: typeof PracticeRoute
  InterviewNewRoute: typeof InterviewNewRoute
  InterviewIdResultRoute: typeof InterviewIdResultRoute
  InterviewIdIndexRoute: typeof InterviewIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/new': {
      id: '/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof InterviewNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id/': {
      id: '/interview/$id/'
      path: '/interview/$id'
      fullPath: '/interview/$id/'
      preLoaderRoute: typeof InterviewIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id/result': {
      id: '/interview/$id/result'
      path: '/interview/$id/result'
      fullPath: '/interview/$id/result'
      preLoaderRoute: typeof InterviewIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  PracticeRoute: PracticeRoute,
  InterviewNewRoute: InterviewNewRoute,
  InterviewIdResultRoute: InterviewIdResultRoute,
  InterviewIdIndexRoute: InterviewIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
